DROP DATABASE IF EXISTS papyrus3;
CREATE DATABASE papyrus3;
USE papyrus3;

CREATE TABLE produit (

CODART      CHAR(4) NOT NULL PRIMARY KEY,
LIBART      VARCHAR(30) NOT NULL,
STKALE      INT(10) NOT NULL,
STKPHY      INT(10) NOT NULL,
QTEANN      INT(10) NOT NULL,
UNIMES      CHAR(5) NOT NULL

);

CREATE TABLE fournis (

NUMFOU      VARCHAR(25) NOT NULL PRIMARY KEY,
NOMFOU      VARCHAR(25) NOT NULL,
RUEFOU      VARCHAR(50) NOT NULL,
POSFOU      CHAR(5) NOT NULL,
VILFOU      VARCHAR(30) NOT NULL,
CONFOU      VARCHAR(15) NOT NULL,
SATISF      ENUM ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10')
);

CREATE TABLE vente (

DELLIV      SMALLINT(5) NOT NULL,
QTE1        INT(10) NOT NULL,
PRIX1       VARCHAR(50) NOT NULL,
QTE2        INT(10),
PRIX2       VARCHAR(50),
QTE3        INT(10),
PRIX3       VARCHAR(50),
NUMFOU      VARCHAR(25) NOT NULL,
CODART      CHAR(4) NOT NULL,
PRIMARY KEY (NUMFOU, CODART),
FOREIGN KEY (NUMFOU) REFERENCES fournis(NUMFOU),
FOREIGN KEY (CODART) REFERENCES produit(CODART)

);

CREATE TABLE entcom (

NUMCOM      INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
OBSCOM      VARCHAR(50),
DATCOM      DATETIME NOT NULL,
NUMFOU      VARCHAR(25),
FOREIGN KEY (NUMFOU) REFERENCES fournis(NUMFOU)

);

CREATE INDEX NUMFOUIND ON entcom(NUMFOU);

CREATE TABLE ligcom (

NUMLIG      TINYINT(3) NOT NULL PRIMARY KEY,
QTECDE      INT(10) NOT NULL,
PRIUNI      VARCHAR(50) NOT NULL,
QTELIV      INT(10),
DERLIV      DATETIME NOT NULL,
NUMCOM      INT(10) NOT NULL,
CODART      CHAR(4) NOT NULL,
FOREIGN KEY (NUMCOM) REFERENCES entcom(NUMCOM),
FOREIGN KEY (CODART) REFERENCES produit(CODART)

);